// packages/toolbar-vue/src/components/collapse/group.vue
<template>
    <div class="toolbar-collapse-group">
        <div v-if="title" class="toolbar-collapse-group-title">{{title}}</div>
        <am-collapse-item
        v-for="item in items"
        :key="item.name"
        :engine="engine"
        v-bind="{...omit(item, 'onClick', 'onDisabled')}"
        :on-click="onClick"
        />
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import { EngineInterface } from '@4399ywkf/engine';
import omit from 'lodash/omit';
import { collapseGroupProps } from '../../types'
import AmCollapseItem from './item.vue'

export default defineComponent({
    name:"am-collapse-group",
    components:{
        AmCollapseItem
    },
    props:collapseGroupProps,
    setup(props){
        const onClick = (event:MouseEvent, name:string, engine?: EngineInterface) => {
            let result;
            const item = props.items.find(item => item.name === name)
            if (item && item.onClick)
                result = item.onClick(event, name, engine);
            if (props.onSelect) props.onSelect(event, name, engine);
            return result;
        }
        return {
            omit,
            onClick
        }
    }
})
</script>

// packages/toolbar/src/color/picker/group.tsx
import React from 'react';
import { EngineInterface } from '@4399ywkf/engine';
import ColorPickerItem from './item';

export type ColorPickerGroupProps = {
	engine: EngineInterface;
	colors: Array<string>;
	activeColors: Array<string>;
	setStroke?: boolean;
	onSelect?: (color: string, event: React.MouseEvent) => void;
};

const ColorPickerGroup: React.FC<ColorPickerGroupProps> = ({
	engine,
	colors,
	activeColors,
	onSelect,
	setStroke,
}) => {
	return (
		<span className="colorpicker-group">
			{colors.map((color) => {
				return (
					<ColorPickerItem
						engine={engine}
						color={color}
						key={color}
						activeColors={activeColors}
						onSelect={onSelect}
						setStroke={setStroke}
					/>
				);
			})}
		</span>
	);
};

export default ColorPickerGroup;
