// packages/toolbar/src/collapse/group.tsx
import React from 'react';
import { EngineInterface } from '@4399ywkf/engine';
import CollapseItem, { CollapseItemProps } from './item';

export type CollapseGroupProps = {
	engine?: EngineInterface;
	title?: React.ReactNode;
	items: Array<Omit<CollapseItemProps, 'engine'>>;
	onSelect?: (
		event: React.MouseEvent,
		name: string,
		engine?: EngineInterface,
	) => void | boolean;
};

const CollapseGroup: React.FC<CollapseGroupProps> = ({
	engine,
	title,
	items,
	onSelect,
}) => {
	return (
		<div className="toolbar-collapse-group">
			{title && (
				<div className="toolbar-collapse-group-title">{title}</div>
			)}
			{items.map((item) => {
				return (
					<CollapseItem
						key={item.name}
						engine={engine}
						{...item}
						onClick={(event, name, engine) => {
							let result;
							if (item.onClick)
								result = item.onClick(event, name, engine);
							if (onSelect) onSelect(event, name, engine);
							return result;
						}}
					/>
				);
			})}
		</div>
	);
};

export default CollapseGroup;

// packages/toolbar-vue/src/components/collapse/group.vue
<template>
    <div class="toolbar-collapse-group">
        <div v-if="title" class="toolbar-collapse-group-title">{{title}}</div>
        <am-collapse-item
        v-for="item in items"
        :key="item.name"
        :engine="engine"
        v-bind="{...omit(item, 'onClick', 'onDisabled')}"
        :on-click="onClick"
        />
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import { EngineInterface } from '@4399ywkf/engine';
import omit from 'lodash/omit';
import { collapseGroupProps } from '../../types'
import AmCollapseItem from './item.vue'

export default defineComponent({
    name:"am-collapse-group",
    components:{
        AmCollapseItem
    },
    props:collapseGroupProps,
    setup(props){
        const onClick = (event:MouseEvent, name:string, engine?: EngineInterface) => {
            let result;
            const item = props.items.find(item => item.name === name)
            if (item && item.onClick)
                result = item.onClick(event, name, engine);
            if (props.onSelect) props.onSelect(event, name, engine);
            return result;
        }
        return {
            omit,
            onClick
        }
    }
})
</script>
